CREATE TABLE "MON_LOG" 
(	
    "ID_MON_LOG" NUMBER NOT NULL IDENTITY, 
	"ID_EXEC_TRASF" NUMBER NOT NULL, 
	"DT_LOG" TIMESTAMP (6) NOT NULL, 
	"CD_LOG" VARCHAR2(30 BYTE), 
	"DS_LOG" CLOB, 
	 PRIMARY KEY ("ID_MON_LOG")
);